--- #YAML:1.0
name:               XTerm-Conf
version:            0.06
abstract:           change configuration of a running xterm
author:
    - Slaven Rezic <srezic@cpan.org>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    Getopt::Long:   2.24
    Term::ReadKey:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
